### ISSUE TITLE
Mock backend

### ISSUE THREAD

**Issue by nicudy** [SENG499-S22-Company3/frontend#66]
Create a mocked API so we can progress while we wait for the backend

**Comment by jayden-chan** [comment]
@SENG499-S22-Company3/frontend I have implemented the mock backend stuff under the `mock-data` branch on the backend repo [here](https://github.com/SENG499-S22-Company3/backend/tree/mock-data). There are some instructions in the readme for how to build and run the backend. Let me know if you have any questions.
